### ISSUE TITLE
Uncaught TypeError on drawImage

### ISSUE THREAD

**Issue by parenko** [educastellano/qr-reader#1]
I got an error :"Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': No function was found that matched the signature provided."
On line qr-reader.html:88, `canvas.drawImage(this.$.video.impl, 0, 0, w, h);`

I solved the problem. But not sure if this is the best solution so far. That's why I am writing this issue and not pulling a request.

Simply by removing `impl` didn't helped. Also calling another `qrcode.decode();` worked not as intended. So I basically copied the part from `decode` method without parameters.

Full diff:

``` diff
@@ -83,11 +84,18 @@
             capture: function () {
                 var w = this.$.video.videoWidth * this.scale,
                     h = this.$.video.videoHeight * this.scale,
-                    canvas = this.$.canvas.getContext('2d');
+                                   b = this.$.canvas,
+                    a = this.$.canvas.getContext('2d');

-                canvas.drawImage(this.$.video.impl, 0, 0, w, h);
+                a.drawImage(this.$.video, 0, 0, w, h);
                 try {
-                    qrcode.decode();
+                                       qrcode.width = b.width;
+                                       qrcode.height = b.height;
+                                       qrcode.imagedata = a.getImageData(0, 0, qrcode.width, qrcode.height);
+                                       qrcode.result = qrcode.process(a);
+                                       if (qrcode.callback != null) {
+                                               qrcode.callback(qrcode.result)
+                                       }
                 }
                 catch (err) {
                     // console.log(err);
```

I am using Chromium Version 40.0.2214.111 on Ubuntu 14.10 (64-bit).

**Comment by educastellano** [comment]
Hi @parenko sorry to answer sooo late, I'm not maintaing this library anymore... If you are still interested in this issue just reopen it or make a PR and I'll take a look :)
